<a href="https://colab.research.google.com/github/Frhan21/Praktikum-Fisika-Komputasi/blob/main/Matriks_Gauss_dan_Gauss_Jordan_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Cara Membuat Array dengan Masukkan / Inputan
import numpy as np 
n = int(input("Masukkan jumlah baris = "))
m = int(input("Masukkan jumlah kolom = "))
a = np.zeros((n,m))

for i in range (0,n):
  for j in range (0,m):
    b = float(input("Masukkan bilangan pada baris ke {} kolom ke {} = ".format(i+1,j+1)))
    a[i][j] = b

print (a)

Masukkan jumlah baris = 3
Masukkan jumlah kolom = 2
Masukkan bilangan pada baris ke 1 kolom ke 1 = 1
Masukkan bilangan pada baris ke 1 kolom ke 2 = 3
Masukkan bilangan pada baris ke 2 kolom ke 1 = 1
Masukkan bilangan pada baris ke 2 kolom ke 2 = 4
Masukkan bilangan pada baris ke 3 kolom ke 1 = 1
Masukkan bilangan pada baris ke 3 kolom ke 2 = 0
[[1. 3.]
 [1. 4.]
 [1. 0.]]


In [ ]:
import numpy as np 
a = np.array([[2,2,1,13],
              [0,3,5,17],
              [0,0,6,6]],float)

N = len(a)
print('===Matriks Awal===')
print (a)

#Metode Back Subtitution 
x =np.zeros((N,1))
x[N-1][0] = a[N-1][N]/a[N-1][N-1]

for i in  range (N-2,-1,-1):
  jum  = 0 
  for j in range (i+1,N):
    jum += a[i][j]*x[j][0]
    x[i][0] = (a[i][N]-jum)/a[i][i]

print()
print('===Nilai x1, x2, x3===')
print(x)

===Matriks Awal===
[[ 2.  2.  1. 13.]
 [ 0.  3.  5. 17.]
 [ 0.  0.  6.  6.]]

===Nilai x1, x2, x3===
[[2.]
 [4.]
 [1.]]


In [ ]:
import numpy as np 

#Soal No 2 
#Mencari segitiga atas dari Matriks 

a = np.array([[11,-13,-8,-20],
             [-9,8,10,-5],
             [-10,3,-1,0]],float)

n = len(a)
print(n)
#Metode Eliminasi Gauss 
for i in range (0,n-1):
  pivot = a[i][i]
  for j in range (i+1,n):
    c = a[j][i]/pivot
    for k in range (i,n+1):
      a[j][k] = a[j][k] - c*a[i][k]

print(a)

3
[[ 11.         -13.          -8.         -20.        ]
 [  0.          -2.63636364   3.45454545 -21.36363636]
 [  0.           0.         -19.82758621  53.27586207]]


In [ ]:
import numpy as np
#Soal No 3
#Metode Eliminasi Gauss cek Pivot 

A = np.array([[0,2,3,18],
              [8,-4,9,26],
              [6,1,7,44]],float)

print (A)
n = len(A)
print()
y = np.zeros((n,n+1))

for i in range (0,n-1):
  if A[i][i]== 0 :
    for j in range (i+1,n):
      if A[j][i] > 0:
        for k in range (0,n+1):
          y[i][j] = A[i][k]
          A[i][k] = A[j][k]
          A[j][k] = y[i][j]
      else : break
  
    
  for i in range (0,n-1):#Masuk Metode Eliminasi Gausss
    pivot = A[i][i]
    for j in range (i+1,n):
      c = A[j][i]/pivot
      for k in range (i,n+1):
        A[j][k] = A[j][k] - c*A[i][k]
 
print()
print(A)
print()
x =np.zeros((n,1))       #Masuk Ke Back Subtitution
x[n-1][0] = A[n-1][n]/A[n-1][n-1]

for i in  range (n-2,-1,-1):
  jum  = 0 
  for j in range (i+1,n):
    jum += A[i][j]*x[j][0]
    x[i][0] = (A[i][n]-jum)/A[i][i]
print()
print(x)

[[ 0.  2.  3. 18.]
 [ 8. -4.  9. 26.]
 [ 6.  1.  7. 44.]]


[[ 6.          1.          7.         44.        ]
 [ 0.          2.          3.         18.        ]
 [ 0.          0.          7.66666667 15.33333333]]


[[4.]
 [6.]
 [2.]]


In [ ]:
#Soal No 4 
import numpy as np

B = np.array([[4,3,2,960],
              [1,3,1,510],
              [2,1,3,610]],float)
n = len(B)

for i in range (0,n):
  pivot = B[i][i]
  for j in range(0,n):
    if j!=i :
      c = B[j][i]/pivot
      for k in range (i,n+1):
        B[j][k] = B[j][k] - c*B[i][k]
        
        # print (B,'\n')
print (B)
print()
x = np.zeros((n,1))

print('===Nilai x1, x2, x3====')
for i in range (n):
  x[i] = B[i][n]/B[i][i]
  print ("x%d = %0.2f"%(i+1,x[i]))



[[  4.           0.           0.         480.        ]
 [  0.           2.25         0.         225.        ]
 [  0.           0.           2.11111111 190.        ]]

===Nilai x1, x2, x3====
x1 = 120.00
x2 = 100.00
x3 = 90.00
