<a href="https://colab.research.google.com/github/Frhan21/Praktikum-Fisika-Komputasi/blob/main/Matriks_Eliminasi_Gauss.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
I = np.array([[1.,-1.,1.,0.],
             [10.,0.,-30.,10.],
             [0.,20.,30.,130.]]) #Matriks yasng dimasukkan adalah matriks yang diperluas 
                                   #Dan matriks yang digunakan adalah matriks 2 dimensi 


# print(I.ndim)
print("Matriks Pertama")
print (I)

print()


#Metode Eliminasi Gauss
#Metode untuk mendapatkan segitiga atas 
n = len(I)
# print(n)

for i in  range (0,n-1):
    pivot = I[i][i]
    for j in range (i+1,n):
        c = I[j][i]/pivot
        for k in range (0,n+1):
            I[j][k] = I[j][k] - c*I[i][k]
print ()
print("Matriks dengan Segitiga Atas")
print(I) #Memprint Matriks dengan segitiga atas 

print()
x = np.zeros((n,1)) #Nilai n,1 itu ----> baris ,kolom 
print(x)
x [n-1][0]= I[n-1][n] / I[n-1][n-1] 
for i in range (n-2,-1,-1): #data yang dimulai dari n-2 indeks 1
    jum = 0 #Inisialisasi
    for j in range(i+1,n):
        jum = jum + I[i][j]*x[j][0]
        x[i][0] =(I[i][n]-jum)/I[i][i]
        
print()
print("Hasil akhir Matriks")
print (x)

Matriks Pertama
[[  1.  -1.   1.   0.]
 [ 10.   0. -30.  10.]
 [  0.  20.  30. 130.]]


Matriks dengan Segitiga Atas
[[  1.  -1.   1.   0.]
 [  0.  10. -40.  10.]
 [  0.   0. 110. 110.]]

[[0.]
 [0.]
 [0.]]

Hasil akhir Matriks
[[4.]
 [5.]
 [1.]]


In [ ]:
#SOAL NO  2 
import numpy as np

T = np.array([[70,1,0,636],
              [60,-1,1,518],
              [40,0,-1,307]],float)   

print("===Matriks Pertama=== ")
print(T)

N = len(T)


#Metode Eliminasi Gauss 
for i in range (0,N-1):
    pivot = T[i][i]
    for j in range (i+1,N):
        C = T[j][i]/pivot
        for k in range (i,N+1):
            T[j][k] = T[j][k] - C*T[i][k]

print("===Matriks Segitiga Atas===")
print(T)

#Metode Subsitusi Mundur 

a = np.zeros((N,1))
a [N-1][0]= T[N-1][N] / T[N-1][N-1]

for i in range (N-2,-1,-1):
    jum = 0
    for j in range(i+1,N):
        jum = jum + T[i][j]*a[j][0]
        a[i][0] =(T[i][N]-jum)/T[i][i]

print("===Hasil Akhir===")
print(a)

===Matriks Pertama=== 
[[ 70.   1.   0. 636.]
 [ 60.  -1.   1. 518.]
 [ 40.   0.  -1. 307.]]
===Matriks Segitiga Atas===
[[ 70.           1.           0.         636.        ]
 [  0.          -1.85714286   1.         -27.14285714]
 [  0.           0.          -1.30769231 -48.07692308]]
===Hasil Akhir===
[[ 8.59411765]
 [34.41176471]
 [36.76470588]]


In [ ]:
def cetakmatriks(matriks):
    for row in matriks:
        print (row)
def pjgmatriks(matriks):
    return len(matriks[0])
def lbrmatriks(matriks):
    return len(matriks[0])
def jumlahmatriks(matA,matB):
    temp_row=[]
    temp_mat=[]
    for i in range(0,lbrmatriks(matA)):
        for j in range(0,pjgmatriks(matA)):
            temp_row.append(matA[i][j]+matB[i][j])
        temp_mat.append(temp_row)
        tempt_row=[]
    return temp_mat

matA=[]
matB=[]
temp_row=[]
n=int(input('Masukkan jumlah ordo: '))
print ('\nMatriks A')
for i in range(n):
    for j in range(n):
        print ('Masukkan elemen [',(i+j),',',(j+i),']',)
        a=int(input(': '))
        temp_row.append(a)
    matA.append(temp_row)
    temp_row=[]
print ('\nMatriks B')
for i in range(n):
    for j in range(n):
        print ('Masukkan elemen [',(i+j),',',(j+i),']',)
        a=int(input(': '))
        temp_row.append(a)
    matB.append(temp_row)
    temp_row=[]
   
print ('\nMatriksA :')
cetakmatriks(matA)
print ('\nmatriksB:')
cetakmatriks(matB)
print ('\nhasil punjumlahan :')
hasil=jumlahmatriks(matA,matB)
cetakmatriks(hasil)



In [ ]:
import numpy as np 
n = int(input("Masukkan jumlah baris = "))
m = int(input("Masukkan jumlah kolom = "))
a = np.zeros((n,m))

for i in range (0,n):
  for j in range (0,m):
    b = float(input("Masukkan bilangan pada baris ke %d kolom ke %d = " %(i+1,j+1)))
    a[i][j] = b

print (a)

Masukkan jumlah baris = 2
Masukkan jumlah kolom = 3
Masukkan bilangan pada baris ke 1 kolom ke 1 = 1
Masukkan bilangan pada baris ke 1 kolom ke 2 = 2
Masukkan bilangan pada baris ke 1 kolom ke 3 = 3
Masukkan bilangan pada baris ke 2 kolom ke 1 = 9
Masukkan bilangan pada baris ke 2 kolom ke 2 = 8
Masukkan bilangan pada baris ke 2 kolom ke 3 = 7
[[1. 2. 3.]
 [9. 8. 7.]]
